---
- name: Instalar ArgoCD CLI no Linux
  hosts: linux
  become: true
  gather_facts: true

  vars:
    argocd_version: "v2.14.10"
    download_path: "/tmp/argocd"

  tasks:

    - name: Baixar ArgoCD CLI
      ansible.builtin.get_url:
        url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-linux-amd64"
        dest: "{{ download_path }}"
        mode: "0755"

    - name: Instalar ArgoCD CLI
      ansible.builtin.copy:
        src: "{{ download_path }}"
        dest: "/usr/local/bin/argocd"
        mode: "0755"
        remote_src: true

    - name: Validar instalação
      ansible.builtin.command:
        cmd: argocd version --client
      register: argocd_result
      changed_when: false

    - name: Exibir versão instalada
      ansible.builtin.debug:
        msg: "{{ argocd_result.stdout }}"